import type { NavItem, Team, Product, BlogPost, SystemStatus } from './types';

// Navigation items
export const NAV_ITEMS: NavItem[] = [
  { label: 'Flag Regulations', path: '/flags', icon: 'Flag' },
  { label: 'Training', path: '/training', icon: 'GraduationCap' },
  { label: 'Knowledge', path: '/knowledge', icon: 'BookOpen' },
  { label: 'Equipment', path: '/products', icon: 'Package' },
  { label: 'Contact', path: '/contact', icon: 'Mail' },
];

export const MOBILE_NAV_ITEMS: NavItem[] = [
  { label: 'Flags', path: '/flags', icon: 'Flag' },
  { label: 'Training', path: '/training', icon: 'GraduationCap' },
  { label: 'Equipment', path: '/products', icon: 'Package' },
  { label: 'More', path: '/menu', icon: 'Menu' },
];

// Brand colors
export const COLORS = {
  brand: {
    teal: '#06B6D4',
    tealDark: '#0891B2',
    navy: '#0F172A',
    slate: '#1E293B',
    red: '#DC2626',
    green: '#10B981',
    yellow: '#F59E0B',
    gray: '#64748B',
  },
  surface: {
    primary: '#FFFFFF',
    secondary: '#F8FAFC',
    tertiary: '#F1F5F9',
  },
};

// Status colors mapping
export const STATUS_COLORS = {
  operational: { bg: 'bg-brand-green', text: 'text-brand-green', label: 'All Systems Operational' },
  degraded: { bg: 'bg-brand-yellow', text: 'text-brand-yellow', label: 'Performance Issues' },
  maintenance: { bg: 'bg-brand-red', text: 'text-brand-red', label: 'Under Maintenance' },
};

// Product status colors
export const PRODUCT_STATUS_COLORS = {
  active: { bg: 'bg-brand-green/10', text: 'text-brand-green', border: 'border-brand-green/20' },
  beta: { bg: 'bg-brand-yellow/10', text: 'text-brand-yellow', border: 'border-brand-yellow/20' },
  deprecated: { bg: 'bg-brand-gray/10', text: 'text-brand-gray', border: 'border-brand-gray/20' },
};

// Mock data for development
export const MOCK_TEAM: Team[] = [
  {
    id: '1',
    name: 'Pavlos-Angelos Filippakis',
    role: 'Managing Director',
    bio: 'Paul founded BlueCross in Estonia in 2020, as a means to create an affordable way for owners to equip their vessels with necessary medical equipment. He is also the Captain of an expedition yacht and an active paramedic in Greece / South Africa.',
    image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/5a54b920-f88c-4848-ab32-9116a792ea13/Profile_Circle_PF/w=400,quality=90,fit=scale-down',
    email: 'paul@bluecross.tech',
    social_links: {
      linkedin: 'https://linkedin.com/company/bluecross-medical',
    },
    order_index: 1,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Athina-Ariadne Filippakis',
    role: 'CMO',
    bio: 'Athina brings her experience managing channels and running marketing campaigns from unicorn startups. She manages client relations and marketing campaigns, along with being the backbone of our CRM.',
    image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/b303388a-7600-4ae5-879c-11c0f2facedc/10556465_10204238388221255_8164821583300425423_n-modified/w=400,quality=90,fit=scale-down',
    email: 'athina@bluecross.tech',
    social_links: {
      linkedin: 'https://linkedin.com/company/bluecross-medical',
    },
    order_index: 2,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Giorgos S. Skafidas',
    role: 'COO / Co-Founder',
    bio: 'George has been in the maritime retail business for over 12 years, co-managing his family\'s marine importation business. He acts as the COO when Paul is onboard and handles the legal aspect of the business.',
    image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/a7112402-d323-43a3-9851-f49725146c30/Untitled_(235__235_px)/w=400,quality=90,fit=scale-down',
    email: 'george@bluecross.tech',
    social_links: {
      linkedin: 'https://linkedin.com/company/bluecross-medical',
    },
    order_index: 3,
    active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Vital Signs Monitor Pro+',
    slug: 'vital-signs-monitor',
    description: 'CE approved all-in-one vital signs monitor. Includes ECG/EKG, SpO2, NIBP, Temperature, Blood Glucose - all in a device weighing just 80g.',
    long_description: 'The Checkme Pro+ Vital Signs Monitor is a pocket-sized medical device that has been tested by seafarers for years. Features a 2.7" HD touch screen, built-in rechargeable battery, and Bluetooth connectivity for iOS/Android/PC. Measures ECG with Lead I & II, SpO2 (70-100% range, ±2% accuracy), heart rate (30-250 bpm), and works with wireless blood pressure cuff. Supports 24-hour Holter monitoring and overnight sleep oxygen tracking. Free PC software and mobile apps included. CE approved with iF Design Award. 1-year warranty and lifetime support. Every purchase supports MEDICO from Hellenic Red Cross.',
    icon_name: 'Heart',
    features: ['ECG/EKG & 24hr Holter', 'SpO2 70-100%', 'Sleep Oxygen Monitor', '2.7" Touch Screen', '80g Lightweight', 'Bluetooth 4.0'],
    image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/143ad6b6-6b0e-4f05-b803-c7086e8a796c/VSP_(1)/w=800,quality=90,fit=scale-down',
    ecwid_product_id: '577895719',
    price: 550,
    status: 'in-stock',
    order_index: 1,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: '12-Lead AI Electrocardiograph',
    slug: '12-lead-ecg',
    description: 'CE approved portable 12-lead ECG with AI analysis. 7" touch screen, WiFi transmission, detects 17+ cardiac events with 95.2% accuracy.',
    long_description: 'The Lepu Neo ECG S120 is a professional 12-lead electrocardiograph with AI-powered diagnosis. Features a 7" high-resolution color touch screen, weighs only 0.8kg, and measures 197mm x 112mm x 26mm. Supports 9 and 12-lead waveforms, automatic pacing detection, respiratory rate analysis, and HRV monitoring. AI platform trained on 50M+ data fragments detects Atrial Fibrillation, Ventricular Tachycardia, and 17+ cardiac events. Outputs PDF, DICOM, HL7, and SCP formats. WiFi and mobile network transmission. Glasgow analysis algorithm. 18-month warranty, 5-year service life. Includes lead wires, electrodes, and carrying case.',
    icon_name: 'Activity',
    features: ['12-Lead ECG', '95.2% AI Accuracy', '7" Touch Screen', '17+ Event Detection', 'WiFi Transmission', '0.8kg Portable'],
    image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/26f68a92-706c-42cd-8b35-02a84c3c98d7/12-lead_Notion_Cover/w=800,quality=90,fit=scale-down',
    ecwid_product_id: '577948909',
    price: 500,
    status: 'in-stock',
    order_index: 2,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Parsys S3 Telemedicine Station',
    slug: 'telemedicine-base-station',
    description: 'Class IIa medical device with 12-lead ECG, oximeter, BP, thermometer, glucometer, stethoscope, spirometer, and ultrasound capability.',
    long_description: 'The Parsys S3 Telemedicine Station is specifically designed for remote maritime environments. Dimensions: 475 x 376 x 178mm, weight: 9kg. Features a 15.6" LED HD touchscreen running Windows 10 Pro with MedCapture software. Includes wireless 12-lead ECG (no consumables), automatic blood pressure monitor, indestructible pulse oximeter, contactless/in-ear thermometer, glucometer, digital stethoscope, spirometer, otoscope, dermatoscope, and optional ultrasound probes. Transmission via WiFi, Ethernet, Bluetooth, or 5G. 6-hour battery with swappable lithium cells. CE 0459 marked, Class IIa medical device per MDR 2017/745. ISO 13485:2016 certified. Designed and assembled in France, deployed on hundreds of vessels worldwide.',
    icon_name: 'Monitor',
    features: ['15.6" HD Touchscreen', '12-Lead Wireless ECG', 'Digital Stethoscope', 'WiFi/5G/Bluetooth', '6hr Battery', 'CE Class IIa'],
    image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/c52c8fd3-dce9-4989-a374-49cb6534f5db/Telemedicine_Base_Station_(1)/w=800,quality=90,fit=scale-down',
    ecwid_product_id: '577956229',
    price: 12500,
    status: 'to-order',
    order_index: 3,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'HeartSine Samaritan PAD 500P',
    slug: 'semi-automatic-defibrillator',
    description: 'Semi-automatic AED with real-time CPR feedback. IP56 rated, 1.1kg, 8-year warranty - the longest in the industry.',
    long_description: 'The HeartSine Samaritan PAD 500P is a semi-automatic defibrillator with integrated CPR Advisor™ technology. Provides real-time visual and verbal feedback on compression depth and rate through the defibrillation pads - no accelerometer pucks needed. Voice prompts guide rescuers with "Push Harder" or "Good Compressions" based on actual cardiac output. IP56 rated for dust and moisture resistance, weighs only 1.1kg. Lowest total cost of ownership - combined Pad-Pak (electrodes + battery) replaced only every 4 years. Semi-automatic operation prevents accidental shocks with untrained personnel. Can increase survival chance for witnessed cardiac arrest up to 85%. 8-year warranty - longest in the industry. CE and FDA approved. Made in EU (Northern Ireland). Every purchase supports MEDICO from Hellenic Red Cross.',
    icon_name: 'Zap',
    features: ['CPR Advisor™ Feedback', '8-Year Warranty', 'IP56 Dust/Moisture', '1.1kg Lightweight', '4-Year Pad-Pak', 'Made in EU'],
    image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/7f19e4a7-df0b-4bca-abee-453050f6f9fb/DeFib_Notion_Cover/w=800,quality=90,fit=scale-down',
    ecwid_product_id: '578004034',
    price: 1600,
    status: 'to-order',
    order_index: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Oxygen Resuscitation Kit',
    slug: 'oxygen-resuscitation-kit',
    description: 'Complete MCA/SOLAS compliant oxygen therapy kit with cylinder, regulator, BVM, and masks for maritime emergency use.',
    long_description: 'Professional oxygen resuscitation kit designed for maritime use and compliant with MCA MSN 1768 and SOLAS requirements. Includes: 2L or 5L aluminum oxygen cylinder (lightweight, corrosion-resistant), adjustable flow regulator (0-15 L/min), adult and pediatric bag valve masks (BVM), oxygen masks with reservoir bags, nasal cannulas, suction device, oropharyngeal airways (sizes 0-5), and durable carry case. Cylinder pressure gauge and flow indicator included. Essential for respiratory emergencies, drowning recovery, smoke inhalation, and cardiac events. Annual inspection certificate provided. Spare cylinders and consumables available.',
    icon_name: 'Wind',
    features: ['MCA/SOLAS Compliant', '2L or 5L Cylinder', 'Adult & Pediatric BVM', '0-15 L/min Regulator', 'Corrosion Resistant', 'Annual Inspection'],
    image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/24552e5d-9512-467b-a55a-86f6892cf0ab/Oxygen_Resuscitation_Kit_-_Notion_Cover_(1)/w=800,quality=90,fit=scale-down',
    status: 'not-available',
    order_index: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Tactical Bleeding Control Kit',
    slug: 'bleeding-control-kit',
    description: 'TCCC-compliant trauma kit with CAT tourniquet, hemostatic gauze, chest seals, and pressure bandages for severe hemorrhage control.',
    long_description: 'Professional bleeding control kit based on Tactical Combat Casualty Care (TCCC) guidelines. Contents: CAT Gen 7 tourniquet (Combat Application Tourniquet), QuikClot Combat Gauze (hemostatic agent), HyFin Vent chest seals (twin pack for entry/exit wounds), Israeli Emergency Bandage (6"), compressed gauze, NPA with lubricant, trauma shears, nitrile gloves, and permanent marker. All items vacuum-sealed in waterproof pouch. Designed for maritime emergency response - treats penetrating trauma, amputations, and severe lacerations. Training guide included with QR code to video tutorials. Compact design fits in bridge emergency station or tender. 3-year shelf life on hemostatic agents.',
    icon_name: 'Shield',
    features: ['CAT Gen 7 Tourniquet', 'QuikClot Hemostatic', 'HyFin Chest Seals', 'Israeli Bandage', 'TCCC Guidelines', 'Waterproof Pouch'],
    image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/01628833-765e-492a-92a1-dcd3d4b6dc01/Bleeding_Control_Kit_Notion_Cover/w=800,quality=90,fit=scale-down',
    status: 'not-available',
    order_index: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_BLOG_POSTS: BlogPost[] = [
  {
    id: '1',
    title: 'What is the M.A.C. and why it matters?',
    slug: 'what-is-the-mac-and-why-it-matters',
    content: 'Medical Advice Center (MAC) of Hellenic Red Cross was established by law in November 1987 and is included in the network of total five (5) Medical Advice Centers established in France, Italy, Greece, Spain and Portugal. The Greek Center moved to Henry Dunant Hospital in 2009.\n\nMAC operates on a 24/7 basis, with the direct support of Henry Dunant Hospital\'s doctors, offering medical advice to any emergency that may occur to passengers and crews onboard commercial or other vessels in all seas around the world, without distinction on the flag ship or nationality.\n\nIn 34 years of operation, MAC\'s work has been recognized by sailors and based on the high levels of services offered naval family has developed absolute confidence.\n\nCapabilities of MAC include:\n- Direct telephone communication from anywhere in the world via satellite, coastal telecommunications network "Olympia Radio" or Hellenic Coast Guard Operation Center.\n- Image Transfer via Internet (e-mail) for more complete information of Physicians, direct and easier response to incidents.\n- Response to incidents (injuries, minor illnesses, minor burns etc.) taking into account the limitation of the pharmaceutical and hospital instruments of ships.\n- For incidents that cannot be addressed on board, relevant advice is given to the master in order to make diversion of the ship to the nearest port.\n\nEmergency numbers: +30 210 523 0880 / +30 210 523 7515\n\nSafe seas!',
    excerpt: 'Medical Advice Center (MAC) of Hellenic Red Cross operates 24/7, offering medical advice to any emergency onboard vessels worldwide.',
    featured_image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/c06cac5e-9405-449f-82f6-dbf89c591715/MAC_Blog_Cover/w=800,quality=90,fit=scale-down',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-01-15T10:00:00Z',
    tags: ['MAC', 'Hellenic Red Cross', 'Emergency', 'Maritime'],
    reading_time_minutes: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'What medicines can be found in a ship\'s medical chest?',
    slug: 'ships-medical-chest-medicines',
    content: 'Every ship in the world carries an inventory of medicines (termed "medical chest"). What is inside that inventory depends on the regulations of each vessel\'s Flag state. Usually, there is a distinction between ocean-going vessels and vessels that sail closer to the coast.\n\nThis list is not exclusive and many companies decide to add additional equipment through their company\'s ISM. After all, you will notice that vital items such as a defibrillator or telemedicine monitor are absent from the "required" list.\n\nMEDICINE CHEST CATEGORIES\n\nThe lists are typically split into 3 categories:\n\nCATEGORY 1: CONTROLLED SUBSTANCES (NARCOTICS)\n\nThese medicines are deemed "narcotics" by the Flag state and must be kept in the custody of the Master, locked away from the rest of the medicine chest in a separate secure location.\n\nExamples include:\n- Morphine sulfate (injectable) - for severe pain\n- Tramadol - moderate to severe pain relief\n- Diazepam - for seizures and severe anxiety\n- Codeine phosphate - pain relief and cough suppression\n\nCATEGORY 2: STANDARD MEDICINES\n\nUsually stored in the ship\'s hospital or medical chest, accessible to designated medical officers.\n\nExamples include:\n- Antibiotics: Amoxicillin, Ciprofloxacin, Metronidazole\n- Pain relief: Paracetamol, Ibuprofen, Aspirin\n- Cardiac: GTN spray, Adrenaline, Atropine\n- Gastrointestinal: Omeprazole, Loperamide, Ondansetron\n- Respiratory: Salbutamol inhaler, Prednisolone\n- Antihistamines: Chlorpheniramine, Hydrocortisone cream\n\nCATEGORY 3: MEDICAL EQUIPMENT\n\nVarious equipment that the vessel needs to have for emergency response and patient care.\n\nExamples include:\n- Resuscitation equipment: Bag valve mask, airways, suction\n- Wound care: Sutures, dressings, splints\n- Diagnostic: Stethoscope, blood pressure monitor, thermometer\n- IV supplies: Cannulas, giving sets, fluids\n\nFLAG STATE REGULATIONS\n\nRequirements vary significantly by Flag state. View our complete Flag State Database for specific requirements: [View Flag Regulations](/flags)',
    excerpt: 'Every ship carries a medical chest. Learn what medicines are required by different Flag states and how to maintain compliance.',
    featured_image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/fbdb23ed-2e95-45ef-bd67-f445c387c3b1/What_medicines_can_be_found_in_a_ships_medical_chest/w=800,quality=90,fit=scale-down',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-01-10T14:00:00Z',
    tags: ['Medical Chest', 'Regulations', 'Maritime', 'Flag State'],
    reading_time_minutes: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Why Every Vessel Needs a Defibrillator',
    slug: 'why-every-vessel-needs-defibrillator',
    content: 'Investing in an AED is a giant step forward because it can increase the chance of survival for witnessed Cardiac Arrest up to 85%.\n\nNot investing in an AED means that in case of a cardiac arrest, when in the high seas, most likely the crew member will die as it not humanly possible to continue CPR indefinitely.\n\nAbout 70% of all CPR is ineffectively performed, so devices like the HeartSine Samaritan 500P Defibrillator contain technology that determines whether your compressions are effective. Voice prompts guide you through the process and tell you to "Push Harder" or whether you are doing "Good Compressions" during CPR – all based on real cardiac output.\n\nKey benefits of the HeartSine 500P:\n- 8-year warranty - longest in the industry\n- Real-time CPR Feedback\n- Lowest maintenance cost - pads and battery renewed only every 4 years\n- IP56 rated for dust & moisture\n- Lightweight at only 1.1kg\n- Made in EU',
    excerpt: 'An AED can increase survival chances for cardiac arrest up to 85%. Learn why every vessel should have one onboard.',
    featured_image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/7f19e4a7-df0b-4bca-abee-453050f6f9fb/DeFib_Notion_Cover/w=800,quality=90,fit=scale-down',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-01-05T09:00:00Z',
    tags: ['Defibrillator', 'AED', 'CPR', 'Safety', 'Maritime'],
    reading_time_minutes: 4,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '4',
    title: 'The Importance of Remote ECG Monitoring at Sea',
    slug: 'importance-remote-ecg-monitoring-sea',
    content: 'Heart disease remains one of the leading causes of death among seafarers. With crew members often working in high-stress environments, far from medical facilities, early detection of cardiac issues is critical.\n\nModern ECG devices like our 12-lead AI Electrocardiographer can detect over 17 types of cardiac events including Atrial Fibrillation, Ventricular Tachycardia, and other arrhythmias. With 95.2% AI accuracy trained on over 50 million data fragments, these devices provide medical-grade reports that can be transmitted remotely to shore-based physicians.\n\nKey advantages of remote ECG monitoring:\n- Early detection of cardiac abnormalities\n- AI-powered analysis for immediate insights\n- Remote transmission to medical professionals\n- Holter monitoring capability for 24-hour assessments\n- Lightweight and portable design perfect for maritime use',
    excerpt: 'Early detection of cardiac issues at sea can save lives. Learn how modern ECG devices are transforming maritime healthcare.',
    featured_image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/26f68a92-706c-42cd-8b35-02a84c3c98d7/12-lead_Notion_Cover/w=800,quality=90,fit=scale-down',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-01-02T10:00:00Z',
    tags: ['ECG', 'Heart Health', 'Telemedicine', 'Maritime', 'AI'],
    reading_time_minutes: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '5',
    title: 'Telemedicine at Sea: The Future of Maritime Healthcare',
    slug: 'telemedicine-at-sea-future-maritime-healthcare',
    content: 'The maritime industry is experiencing a healthcare revolution with the adoption of advanced telemedicine systems. The S3 Base Station represents the most advanced telemedicine solution specifically designed for remote maritime environments.\n\nFeatures that make modern telemedicine essential:\n- Works offline and transmits via low bandwidth systems like FBB\n- Patented pad-free ECG technology for quick readings\n- HIPAA/HDS compliant data storage\n- Integration with 24/7 medical advice centers\n- Digital stethoscope for remote respiratory assessment\n\nWith proper telemedicine equipment, vessels can connect with shore-based physicians in real-time, ensuring crew members receive expert medical guidance regardless of their location at sea.',
    excerpt: 'Modern telemedicine systems are revolutionizing healthcare delivery at sea. Discover the latest in maritime medical technology.',
    featured_image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/c52c8fd3-dce9-4989-a374-49cb6534f5db/Telemedicine_Base_Station_(1)/w=800,quality=90,fit=scale-down',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2023-12-28T14:00:00Z',
    tags: ['Telemedicine', 'Maritime', 'Technology', 'Healthcare', 'Remote'],
    reading_time_minutes: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '6',
    title: 'Captain Richard\'s Story: Why Crew Health Monitoring Matters',
    slug: 'captain-richards-story-crew-health-monitoring',
    content: 'Imagine Captain Richard - 20 years with your fleet, mid-fifties, two packs a day. He is currently alongside a port in China during Covid measures. At 08:00 LT, he is found unconscious and without a pulse. There is no defibrillator on board.\n\nThis scenario, while extreme, highlights the reality many shipping companies face. Heart disease is a leading cause of death at sea, and preventive monitoring can make the difference between life and death.\n\nWhat if Captain Richard had access to weekly ECG monitoring through a portable Vital Signs Pro+ device? The early warning signs of cardiac issues could have been detected and addressed before a crisis occurred.\n\nKey takeaways:\n- High-risk crew members need regular monitoring\n- Portable devices make monitoring feasible at sea\n- Early detection saves lives and reduces costs\n- P&I clubs increasingly recognize the value of preventive care',
    excerpt: 'A fictional but realistic scenario that illustrates the life-saving importance of crew health monitoring at sea.',
    featured_image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/143ad6b6-6b0e-4f05-b803-c7086e8a796c/VSP_(1)/w=800,quality=90,fit=scale-down',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2023-12-20T09:00:00Z',
    tags: ['Crew Health', 'Prevention', 'Maritime', 'Safety', 'Case Study'],
    reading_time_minutes: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '7',
    title: 'Recognizing and Responding to Heart Attacks at Sea',
    slug: 'recognizing-responding-heart-attacks-at-sea',
    content: 'Heart attacks are the leading cause of death among seafarers (30-40% of all deaths onboard). This checklist will help you recognize and respond effectively.\n\nCHECKLIST: RECOGNIZE THE SIGNS\n\n[ ] Chest pain or pressure lasting more than a few minutes\n[ ] Pain spreading to left arm, neck, jaw, or back\n[ ] Shortness of breath\n[ ] Cold sweats\n[ ] Nausea or vomiting\n[ ] Lightheadedness or dizziness\n[ ] Unusual fatigue (especially in women)\n\nCHECKLIST: IMMEDIATE ACTIONS\n\n1. ALERT - Call the bridge and request TMAS contact immediately\n2. POSITION - Sit patient upright at 45 degrees (semi-recumbent) to reduce heart workload\n3. ASPIRIN - Give 300mg aspirin to chew (ask about allergies first)\n4. OXYGEN - Check SpO2 with pulse oximeter. Give oxygen if below 94%\n5. REASSURE - Keep patient calm and still. Loosen tight clothing\n6. MONITOR - Check pulse and breathing every 2 minutes\n7. AED READY - Have defibrillator nearby in case of cardiac arrest\n8. DOCUMENT - Write down time symptoms started and all actions taken\n\nWARNING SIGNS OF CARDIAC ARREST\n\n[ ] Patient becomes unresponsive\n[ ] No normal breathing (or only gasping)\n[ ] No pulse\n\nIf any of these occur, START CPR IMMEDIATELY and use AED.',
    excerpt: 'Step-by-step checklist for recognizing and responding to heart attacks at sea. Print and post in ship hospital.',
    featured_image_url: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=800&q=80',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-02-15T10:00:00Z',
    tags: ['Heart Attack', 'Emergency', 'First Aid', 'Maritime', 'Checklist'],
    reading_time_minutes: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '8',
    title: 'Severe Allergic Reactions (Anaphylaxis): Emergency Checklist',
    slug: 'severe-allergic-reactions-anaphylaxis-at-sea',
    content: 'Anaphylaxis can kill within minutes. This checklist will help you act fast with limited resources.\n\nCHECKLIST: RECOGNIZE ANAPHYLAXIS\n\n[ ] Difficulty breathing or wheezing\n[ ] Swelling of tongue, throat, or lips\n[ ] Widespread hives or skin flushing\n[ ] Rapid or weak pulse\n[ ] Dizziness or fainting\n[ ] Nausea, vomiting, or abdominal pain\n[ ] Sense of doom or confusion\n\nCOMMON TRIGGERS TO ASK ABOUT\n\n[ ] Shellfish, fish, nuts, eggs, or milk\n[ ] Insect sting (bee, wasp)\n[ ] Medication taken recently\n[ ] Latex contact\n\nCHECKLIST: IMMEDIATE ACTIONS\n\n1. EPINEPHRINE FIRST - This is the priority. Locate adrenaline in medical chest\n2. INJECT - Give 0.5ml of 1:1000 adrenaline into OUTER THIGH muscle (through clothing if needed)\n3. CALL TMAS - Get medical advice while treating\n4. POSITION - Lie patient flat with legs raised. If breathing difficulty, let them sit up\n5. OXYGEN - Give high-flow oxygen if available\n6. MONITOR - Check breathing and pulse every minute\n7. REPEAT - If no improvement after 5 minutes, give second adrenaline dose\n8. ANTIHISTAMINE - Give Chlorpheniramine 10mg IM as secondary treatment\n\nIF PATIENT BECOMES UNRESPONSIVE\n\n[ ] Check for breathing\n[ ] If not breathing normally, start CPR\n[ ] Continue until help arrives or patient recovers\n\nIMPORTANT: Symptoms can return hours later. Monitor patient for at least 6 hours.',
    excerpt: 'Emergency checklist for anaphylaxis. Epinephrine first, ask questions later. Every second counts.',
    featured_image_url: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=800&q=80',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-02-10T14:00:00Z',
    tags: ['Anaphylaxis', 'Allergic Reaction', 'Emergency', 'First Aid', 'Checklist'],
    reading_time_minutes: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '9',
    title: 'Oxygen Administration: Quick Reference Guide',
    slug: 'oxygen-administration-at-sea-practical-guide',
    content: 'Oxygen can save lives but must be used correctly. This guide tells you when and how to give oxygen with ship equipment.\n\nCHECKLIST: WHEN TO GIVE OXYGEN\n\n[ ] SpO2 reading below 94% on pulse oximeter\n[ ] Difficulty breathing or shortness of breath\n[ ] Chest pain (possible heart attack)\n[ ] After drowning or near-drowning\n[ ] Severe bleeding or shock\n[ ] Carbon monoxide exposure\n[ ] Unconscious patient\n\nCHECKLIST: BEFORE STARTING\n\n1. CHECK cylinder pressure gauge - is there enough oxygen?\n2. ENSURE no smoking or flames nearby\n3. SELECT correct delivery device for patient condition\n4. ATTACH pulse oximeter to monitor response\n\nDELIVERY METHOD QUICK GUIDE\n\nNASAL CANNULA (Conscious, mild symptoms)\n- Flow rate: 2-4 L/min\n- Delivers: 24-35% oxygen\n- Use for: Alert patients with mild breathing difficulty\n\nFACE MASK (Conscious, moderate symptoms)\n- Flow rate: 6-10 L/min (minimum 5 L/min)\n- Delivers: 40-60% oxygen\n- Use for: Moderate breathing difficulty\n\nNON-REBREATHER MASK (Serious symptoms)\n- Flow rate: 10-15 L/min\n- Delivers: 60-90% oxygen\n- Use for: Severe breathing difficulty, shock, chest pain\n- CHECK: Reservoir bag must stay inflated\n\nBAG VALVE MASK (Not breathing)\n- Flow rate: 15 L/min connected to bag\n- Use for: Unconscious patient not breathing\n- SQUEEZE bag once every 5-6 seconds\n\nSAFETY REMINDERS\n\n[ ] No oil or grease on equipment\n[ ] Secure cylinder to prevent falling\n[ ] Monitor patient response\n[ ] Document flow rate and time started',
    excerpt: 'Quick reference for oxygen administration. Know which device to use and at what flow rate.',
    featured_image_url: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?w=800&q=80',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-02-05T09:00:00Z',
    tags: ['Oxygen', 'Respiratory', 'Emergency', 'First Aid', 'Checklist'],
    reading_time_minutes: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '10',
    title: 'How to Use an AED: Step-by-Step Checklist',
    slug: 'how-to-use-aed-defibrillator-step-by-step',
    content: 'An AED can increase survival from cardiac arrest to 85%. The device talks you through it. Follow this checklist.\n\nCHECKLIST: WHEN TO USE AED\n\n[ ] Person is unresponsive (does not respond when you shout and tap shoulders)\n[ ] Not breathing normally (no breathing, or only occasional gasps)\n[ ] No pulse (check at neck for 10 seconds maximum)\n\nIf ALL THREE are present, this is CARDIAC ARREST. Use AED immediately.\n\nSTEP-BY-STEP CHECKLIST\n\n1. SAFETY - Check area is safe. Move patient from water if wet deck\n2. CALL FOR HELP - Shout for assistance. Send someone for AED\n3. START CPR - Begin chest compressions while waiting for AED\n4. TURN ON AED - Press power button. Listen to voice prompts\n5. BARE CHEST - Remove or cut clothing. Dry chest if wet\n6. ATTACH PADS - Peel backing off pads. Place as shown on pads:\n   - Right pad: Below right collarbone\n   - Left pad: Left side, below armpit\n7. PLUG IN - Connect pads cable to AED if not pre-connected\n8. STAND CLEAR - Ensure nobody is touching patient. Say "ANALYZING"\n9. FOLLOW PROMPTS - AED will say "Shock advised" or "No shock advised"\n10. IF SHOCK ADVISED - Say "CLEAR!" loudly. Check nobody touching. Press shock button\n11. RESUME CPR - Immediately after shock, do 30 compressions then 2 breaths\n12. CONTINUE - Follow AED prompts. It will re-analyze every 2 minutes\n\nSPECIAL SITUATIONS\n\n[ ] Hairy chest: Shave area or press pads firmly\n[ ] Medication patch: Remove patch, wipe area\n[ ] Pacemaker (lump under skin): Place pad at least 3cm away\n[ ] Wet patient: Dry chest before attaching pads\n[ ] Child under 8: Use pediatric pads if available',
    excerpt: 'AED step-by-step checklist. The device guides you with voice prompts. Follow these steps.',
    featured_image_url: 'https://images.spr.so/cdn-cgi/imagedelivery/j42No7y-dcokJuNgXeA0ig/7f19e4a7-df0b-4bca-abee-453050f6f9fb/DeFib_Notion_Cover/w=800,quality=90,fit=scale-down',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-01-25T10:00:00Z',
    tags: ['AED', 'Defibrillator', 'CPR', 'Cardiac Arrest', 'Checklist'],
    reading_time_minutes: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '11',
    title: 'Scabies Onboard: Identification and Treatment Checklist',
    slug: 'scabies-onboard-prevention-identification-treatment',
    content: 'Scabies spreads fast in ship living quarters. Early identification and proper treatment prevents outbreaks.\n\nCHECKLIST: RECOGNIZE SCABIES\n\n[ ] Intense itching, especially at night\n[ ] Small red bumps or blisters\n[ ] Thin, irregular burrow tracks on skin\n[ ] Symptoms in multiple crew members\n\nCOMMON LOCATIONS TO CHECK\n\n[ ] Between fingers\n[ ] Wrists and inner elbows\n[ ] Armpits\n[ ] Waistline and belt area\n[ ] Buttocks\n[ ] Genitals\n\nNote: First infection takes 4-6 weeks for symptoms. Re-infection shows symptoms in 1-4 days.\n\nTREATMENT CHECKLIST\n\n1. CONTACT TMAS - Confirm diagnosis before treatment\n2. ISOLATE - Keep infected person in own cabin if possible\n3. TREAT PATIENT:\n   - Apply Permethrin 5% cream from neck to toes\n   - Cover ALL skin including between fingers, under nails\n   - Leave on for 8-14 hours (overnight)\n   - Wash off in shower\n   - REPEAT after 7 days\n4. TREAT CONTACTS - All cabin mates and close contacts, even without symptoms\n5. WASH EVERYTHING:\n   - All bedding, towels, clothing in HOT water (60°C minimum)\n   - Items that cannot be washed: seal in plastic bag for 72 hours\n6. CLEAN CABIN:\n   - Vacuum mattress and furniture\n   - Wipe surfaces\n\nALTERNATIVE IF NO PERMETHRIN\n\nOral Ivermectin: Single dose of 200 micrograms per kg body weight. Repeat after 7 days.\n\nPREVENTION CHECKLIST\n\n[ ] Regular cabin inspections\n[ ] Report itching early\n[ ] Do not share towels, bedding, or clothing\n[ ] Screen new crew joining vessel',
    excerpt: 'Scabies identification and treatment checklist. Act fast to prevent shipwide outbreak.',
    featured_image_url: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?w=800&q=80',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-01-20T14:00:00Z',
    tags: ['Scabies', 'Skin Conditions', 'Infectious Disease', 'Checklist'],
    reading_time_minutes: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '12',
    title: 'Stroke at Sea: FAST Recognition Checklist',
    slug: 'stroke-at-sea-recognition-emergency-response',
    content: 'Stroke kills brain cells every minute. Quick recognition and response is critical. Use this FAST checklist.\n\nFAST CHECKLIST - CHECK ALL FOUR\n\n[ ] F - FACE: Ask person to smile. Does one side droop?\n[ ] A - ARMS: Ask to raise both arms. Does one drift down?\n[ ] S - SPEECH: Ask to repeat "The sky is blue." Is it slurred or strange?\n[ ] T - TIME: Note the exact time symptoms started. Call TMAS immediately.\n\nIf ANY of these are present, treat as stroke emergency.\n\nADDITIONAL WARNING SIGNS\n\n[ ] Sudden severe headache (worst headache ever)\n[ ] Sudden confusion or trouble understanding\n[ ] Sudden vision problems in one or both eyes\n[ ] Sudden trouble walking or loss of balance\n[ ] Sudden numbness on one side of body\n\nCHECKLIST: IMMEDIATE ACTIONS\n\n1. NOTE TIME - Write down when symptoms started (critical for treatment)\n2. CALL TMAS - Stroke requires urgent medical advice\n3. POSITION PATIENT:\n   - If conscious: Sit up with head elevated 30 degrees\n   - If unconscious: Recovery position (on side)\n4. CHECK AIRWAY - Ensure patient can breathe\n5. MONITOR - Check breathing and pulse every 2 minutes\n6. OXYGEN - Give if SpO2 below 94%\n7. DO NOT GIVE ASPIRIN - Unlike heart attack, aspirin can make stroke worse\n8. PREPARE FOR EVACUATION - Stroke patients need hospital urgently\n\nWHILE WAITING FOR EVACUATION\n\n[ ] Keep patient calm and quiet\n[ ] Do not give food or water (swallowing may be affected)\n[ ] Keep monitoring vital signs\n[ ] Document all observations for medical team\n[ ] If patient becomes unresponsive, check breathing and be ready for CPR',
    excerpt: 'FAST stroke recognition checklist. Face, Arms, Speech, Time. Every minute counts.',
    featured_image_url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-01-18T09:00:00Z',
    tags: ['Stroke', 'Emergency', 'Neurological', 'First Aid', 'Checklist', 'FAST'],
    reading_time_minutes: 5,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '13',
    title: 'CPR: Step-by-Step Checklist for Seafarers',
    slug: 'cpr-step-by-step-checklist-seafarers',
    content: 'CPR keeps blood flowing to the brain until the heart restarts. Quality compressions are more important than rescue breaths. Follow this checklist.\n\nCHECKLIST: WHEN TO START CPR\n\n[ ] Person is unresponsive (does not respond to shouting and shoulder tap)\n[ ] Not breathing normally (no breathing, or only occasional gasps)\n[ ] No pulse (check at neck for maximum 10 seconds)\n\nIf ALL THREE are present, START CPR IMMEDIATELY.\n\nBEFORE STARTING\n\n1. ENSURE SAFETY - Check scene is safe for you\n2. CALL FOR HELP - Shout for assistance. Send someone for AED\n3. POSITION PATIENT - On back, on firm surface (deck, not bed)\n\nCPR STEP-BY-STEP\n\n1. KNEEL beside patient at chest level\n2. PLACE HANDS:\n   - Find center of chest (between nipples)\n   - Place heel of one hand on center of chest\n   - Place other hand on top, fingers interlocked\n3. POSITION YOUR BODY:\n   - Arms straight, shoulders directly over hands\n   - Keep your back straight\n4. COMPRESS:\n   - Push down HARD - at least 5cm (2 inches) deep\n   - Push FAST - 100-120 compressions per minute (beat of Stayin\' Alive)\n   - Let chest fully recoil between compressions\n   - Do not lean on chest between compressions\n5. COUNT: 30 compressions\n6. GIVE 2 BREATHS (if trained):\n   - Tilt head back, lift chin\n   - Pinch nose closed\n   - Seal your mouth over theirs\n   - Blow for 1 second, watch chest rise\n   - Give second breath\n7. CONTINUE: 30 compressions, 2 breaths. Do not stop.\n\nIF YOU ARE ALONE OR UNTRAINED\n\nHands-only CPR is acceptable:\n- Continuous chest compressions at 100-120 per minute\n- Do not stop until help arrives or patient recovers\n\nWHEN TO STOP CPR\n\n[ ] AED is attached and analyzing\n[ ] Patient starts breathing normally\n[ ] Qualified medical help takes over\n[ ] You are too exhausted to continue (swap with another rescuer)\n\nCOMMON MISTAKES TO AVOID\n\n[ ] Compressions too shallow - Push HARD\n[ ] Compressions too slow - Push FAST\n[ ] Leaning on chest between compressions\n[ ] Stopping for too long to give breaths\n[ ] Giving up too early',
    excerpt: 'CPR checklist for seafarers. Push hard, push fast, do not stop. This guide saves lives.',
    featured_image_url: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800&q=80',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-02-20T10:00:00Z',
    tags: ['CPR', 'Cardiac Arrest', 'Emergency', 'First Aid', 'Checklist'],
    reading_time_minutes: 6,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: '14',
    title: 'Airway Obstruction: Choking Emergency Checklist',
    slug: 'airway-obstruction-choking-emergency-checklist',
    content: 'A blocked airway can kill in minutes. This checklist covers choking and basic airway management with ship resources.\n\nCHECKLIST: RECOGNIZE CHOKING\n\nMILD OBSTRUCTION (can still breathe):\n[ ] Coughing forcefully\n[ ] Can speak or make sounds\n[ ] Can breathe between coughs\n\nSEVERE OBSTRUCTION (cannot breathe):\n[ ] Cannot speak or only whispers\n[ ] Cannot cough effectively\n[ ] Clutching throat (universal choking sign)\n[ ] Face turning blue\n[ ] Making high-pitched sounds or no sound\n[ ] Becoming unconscious\n\nCHECKLIST: CONSCIOUS ADULT CHOKING\n\n1. ASK - "Are you choking? Can you speak?"\n2. IF MILD (can cough): Encourage forceful coughing. Stay with them.\n3. IF SEVERE (cannot cough or speak):\n\nBACK BLOWS:\n- Stand to side and slightly behind\n- Support chest with one hand\n- Give 5 sharp blows between shoulder blades with heel of hand\n\nABDOMINAL THRUSTS (if back blows fail):\n- Stand behind patient\n- Make fist with one hand\n- Place fist just above belly button (below ribs)\n- Grasp fist with other hand\n- Pull sharply inward and upward\n- Give 5 thrusts\n\n4. ALTERNATE - 5 back blows, then 5 abdominal thrusts. Repeat until object clears or patient becomes unconscious.\n\nCHECKLIST: UNCONSCIOUS CHOKING\n\n1. LOWER patient carefully to deck\n2. CALL FOR HELP - Send for AED\n3. START CPR - Begin with 30 chest compressions\n4. CHECK MOUTH - Before giving breaths, look in mouth for visible object\n5. REMOVE OBJECT - Only if you can see it. Use finger sweep\n6. ATTEMPT BREATHS - Tilt head, lift chin, try 2 breaths\n7. IF CHEST DOES NOT RISE - Reposition head and try again\n8. CONTINUE CPR - 30 compressions, check mouth, 2 breaths. Repeat.\n\nBASIC AIRWAY MANAGEMENT\n\nFor unconscious patient who IS breathing:\n\n1. HEAD TILT-CHIN LIFT:\n   - Place hand on forehead\n   - Tilt head back gently\n   - Lift chin with fingertips under jaw bone\n   - This opens the airway\n\n2. RECOVERY POSITION:\n   - Roll patient onto side\n   - Top leg bent at knee for stability\n   - Hand under cheek\n   - Monitor breathing continuously\n\nWHEN TO USE AIRWAY DEVICES\n\nOropharyngeal Airway (OPA):\n- Only for unconscious patients with no gag reflex\n- Measure from corner of mouth to earlobe\n- Insert upside down, then rotate 180 degrees\n\nIMPORTANT: If patient gags or vomits, remove immediately and turn on side.',
    excerpt: 'Choking and airway emergency checklist. Back blows, abdominal thrusts, and basic airway management.',
    featured_image_url: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=800&q=80',
    author_name: 'BlueCross Medical',
    published: true,
    published_at: '2024-02-22T10:00:00Z',
    tags: ['Airway', 'Choking', 'Emergency', 'First Aid', 'Checklist'],
    reading_time_minutes: 7,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const MOCK_SYSTEM_STATUS: SystemStatus = {
  id: '1',
  status: 'operational',
  message: 'All systems are running smoothly.',
  severity: 0,
  updated_at: new Date().toISOString(),
};

// Tech stack items
export const TECH_STACK = [
  { name: 'React', category: 'Frontend', icon: 'Code2' },
  { name: 'TypeScript', category: 'Language', icon: 'FileCode' },
  { name: 'Node.js', category: 'Backend', icon: 'Server' },
  { name: 'PostgreSQL', category: 'Database', icon: 'Database' },
  { name: 'Supabase', category: 'Platform', icon: 'Cloud' },
  { name: 'Tailwind CSS', category: 'Styling', icon: 'Palette' },
  { name: 'Vercel', category: 'Hosting', icon: 'Globe' },
  { name: 'HIPAA', category: 'Compliance', icon: 'Shield' },
];

// Company info
export const COMPANY_INFO = {
  name: 'BlueCross Medical',
  tagline: 'Maritime Emergency Medicine',
  description: 'Your complete resource for emergency medicine at sea. Flag state regulations, advanced training courses, knowledge articles, and tested equipment - all in one place.',
  email: 'sales@bluecross.tech',
  phone: '+30 698 672 0525',
  emergencyPhone: '+30 210 523 0880',
  address: 'Frynis 55, Athens, Greece',
  workingHours: 'Mon-Fri 09:00 - 18:00 (EET/EEST)',
  social: {
    linkedin: 'https://app.medicoguide.no/p/t/d8c084c3-f3b4-4369-6086-08d7f8ead50e',
    twitter: '#',
    facebook: '#',
  },
};

// API timeout
export const API_TIMEOUT = 30000;
