version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "development"
    groups:
      all-dependencies:
        patterns:
          - "*"
    labels:
      - "dependabot"
    commit-message:
      prefix: "deps"
